name: CI/CD for Flask App on Azure

on:
  push:
    branches:
      - main  # Runs when changes are pushed to 'main' branch
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: |
          if [ -d "tests" ]; then
            python -m unittest discover tests
          else
            echo "No tests found, skipping tests."
          fi

  build-and-deploy:
    name: Build & Deploy to Azure
    runs-on: ubuntu-latest
    needs: test  # Runs only if tests pass

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker Image to Azure Container Registry
        run: |
          docker build -t myflaskapp:latest .
          az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          docker tag myflaskapp:latest ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/myflaskapp:latest
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/myflaskapp:latest

      - name: Deploy to Azure App Service
        run: |
          az webapp config container set \
            --name "mypython-app" \
            --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" \
            --docker-custom-image-name "${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/myflaskapp:latest" \
            --docker-registry-server-url "https://${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io" \
            --docker-registry-server-user "${{ secrets.AZURE_REGISTRY_USERNAME }}" \
            --docker-registry-server-password "${{ secrets.AZURE_REGISTRY_PASSWORD }}"

      - name: Logout from Azure
        run: az logout


    

